### PR TITLE
Unification Proposal

### PR DESCRIPTION
**Pull request by pramsey**
Solving some issues raised by bringing together groups and collections, adding some flags and another (!) optional slot.

### CODE REVIEW

**Comment by nicklasaven** [comment]
I think I see the logic. 
three questions:
why change order of type-byte and meta-data byte? I see no problem with that, but just curios about why. It means, I guess that you want to repeat also the meta-data byte in the collection for each sub geometry,? THat was the reason for doing it the other way. To define the meta-byte as "once for whole twkb" and then have the same flow for the rest.

Second question. Why have multiple npoints[] in polygon and some others? Isn't that the thing with the npoints-array that it holds all npoints-values for all rings?

Third question:
Why not permit negative precision on optional extra precision-byte when there is 2 unused bits? 
 

What I see is the trade off here is an extra ngeoms-byte for single geoemtries with an id. But I think it might be worth that because the spec gets less complicated. I want to think a little more about if this covers all wanted cases.

**Comment by pramsey** [comment]
1st - Why change order? Because "type first" is something I feel happier with. Also, if you're dropping the metadata header sometimes, that means it's semi-optional... it's kind of important to have around on sub-geometries too, since the sub-geometries may have different components optionally in or out, otherwise you have a whole bunch of implicit unspecified rules lying around (do sub-geometries always get bounding boxes? sometimes? when? why?)

2nd - My notation on the npoints stuff is probably confusing things: lacking an actual subscript I used that notation, so it looks like an array where it's really not. It's just the 'nth' instance of an npoints attribute.

3rd - Just didn't think negative precision was something that was going to be used for those cases. Or lots of precision (7 digits) so I provided less space for them and removed negative as an option. This is the problem with hoarding every bit.

**Comment by nicklasaven** [comment]
1st - Ok, but that makes type 7 quite special. A bunch of linestrings in type 5 doesn't have any options between sub geoemtries, but the same linestrings if forced into type 7 do have that options (like some with ID, some without, diffeent percission and so on. 

From my point of view we can live with that special treatment, but I think it is close to be categorized as an ugliness. I could also live with forcing all sub geoemtries to obey one master header, like in geometry collections with g_serialized. The sub geoemtries have their own type, but the same header.

2nd - I see, great

3rd - I just don't see any usage of the empty 2 bits, so they could be used for signing the 2 values.
Or should the 2 unused bits be used to tell "absolute or relative".

**Comment by javisantana** [comment]
my concerns:

- a single point would take 4 bytes as minimum because of that new metadata byte. Not a big deal but before it was 1 byte less which is significative size change

- the point of homogeneous group was to avoid to send metadata for each geometry, if you unify it with geometrycollection it basically sends the metadata for each geometry, rigth?

**Comment by nicklasaven** [comment]
What Paul calls metadata-byte is what we before called header-byte. So it has been there all the time. 4 bytes was smallest point size also before

**Comment by pramsey** [comment]
The multi* types when used with the optional "idlist" serve the purpose of the old "homogeneous collection" pretty much exactly as far as I can tell. They are a minimally sized group of feature with external ids to tie back to the data source.

**Comment by pramsey** [comment]
WRT the precision of the extra dimensions, one reason for keeping them to 3 bits each is to leave 2 unused bits lying around the spec.

**Pull request merged**
